Currently broken; You need to create a user object and then an event object with that user; Running into the following issue when creating a user (AttributeError: 'Table' object has no attribute 'owner_id')